### ISSUE TITLE
Ashvatthama

### ISSUE THREAD

**Issue by aacknov** [Simon73me/Fate-Waifugram#1]
I'm not sure if it's a problem somewhere in the code or just that we haven't found the correct spelling, but no matter how we typed ashvatthama's name it just wasn't acceptable for the bot. So if there isn't a problem in the coding please send the correct way to spell the name.

**Comment by Simon73me** [comment]
Hi thanks for the report
The name saved on the db was Ashvatthaman, I picked this name from FGO wiki
Now I've changed it into Ashwatthama that should be the correct spelling
